[package]
name = "cmyk_press_renderer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
after-effects = { git = "https://github.com/virtualritz/after-effects.git" }
num_cpus = "1.17"
rayon = "1.10"

[target.'cfg(target_os = "macos")'.dependencies]
foreign-types = "0.5"
metal = "0.31"

[build-dependencies]
pipl = { git = "https://github.com/virtualritz/after-effects.git" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
